### ISSUE TITLE
Can't break Sound Muffler

### ISSUE THREAD

**Issue by NotMyFault** [InventivetalentDev/SoundMuffler#27]
## What steps will reproduce the problem?  
1. Get the Sound Muffler and the Packet Listener api on a 1.15.2 server (tested on Paper 213)
2. Craft a muffler and place it
3. Try to break it

## What were you expecting to happen? What happened instead?  
I tried to (shift) right/leftclick to break the muffler but nothing happened. Yet it does its job.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
1.0.5-SNAPSHOT

## What Spigot version are you using? *Type /version*  
git-Paper-213 (MC: 1.15.2)

## What plugins are you using? *Type /plugins*  
Essentials, LuckPerms, Multiverse-Core, PacketListenerApi*, PlotSquared, SoundMuffler, Vault, WorldEdit

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
The log is clean, but I'll provide it still: https://pastebin.com/9N0J7yVs

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well* 
Nope

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Nope

**Comment by TommyAGK** [comment]
Same issue
