### ISSUE TITLE
Can't break soundmuffler (1.14.4)

### ISSUE THREAD

**Issue by TheGamingChris** [InventivetalentDev/SoundMuffler#28]
## What steps will reproduce the problem?  
1. Craft a SoundMuffler
2. Place a SoundMuffler

## What were you expecting to happen? What happened instead?  
Try to break a SoundMuffler won't work. (With or without sneaking)
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
1.0.5-SNAPSHOT
## What Spigot version are you using? *Type /version*  
git-Spigot-56f8471-6567017 (MC: 1.14.4)
## What plugins are you using? *Type /plugins*  
Plugins (3): LuckPerms, PacketListenerApi, SoundMuffler
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
No errors
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I tried previous versions. No version work :/

**Comment by Fundryi** [comment]
Hello, this is still relevant, it doesn't work on 1.16 either.
I really don't know how I can remove it now...
